"""add archive

Revision ID: 96abb54b0498
Revises: 300eb1557bab
Create Date: 2021-09-14 21:03:40.639523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96abb54b0498'
down_revision = '300eb1557bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_model', sa.Column('archive', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_model', 'archive')
    # ### end Alembic commands ###
