"""Add db for images

Revision ID: fef2211415c0
Revises: 96abb54b0498
Create Date: 2021-09-17 17:24:08.752514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef2211415c0'
down_revision = '96abb54b0498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url')
    )
    op.add_column('user_model', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_model', 'image', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_model', type_='foreignkey')
    op.drop_column('user_model', 'image_id')
    op.drop_table('image')
    # ### end Alembic commands ###
